name = "Firecrest Responsive"
license = "MIT"
licenselink = "https://github.com/fsLeg/firecrest-resp/blob/master/LICENSE"
description = "A port of Firecrest-resp theme from Chyrp which was a Bootstrap port of the original Firecrest."
homepage = "https://github.com/fsLeg/firecrest-resp"
tags = ["blog", "chyrp", "responsive"]
features = ["feathers", "bootstrap", "video player", "fancybox"]
min_version = "0.60.0"

[author]
  name = "fsLeg"
  homepage = "https://github.com/fsLeg"

# If porting an existing theme
[original]
  name = "Firecrest"
  homepage = "http://chyrp.net"
  repo = "https://github.com/chyrp/chyrp/tree/develop/themes/firecrest"
